import { siteConfig } from '@/configs/site'
import '@/styles/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.subName}`,
  },
  description: 'Generated by create next app',
  icons: '/icon.png',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="scroll-smooth font-sans antialiased">{children}</body>
    </html>
  )
}
