/* eslint-disable import/order */
import RQProvider from '@/components/provider'
import { siteConfig } from '@/configs/site'

import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: {
    default: siteConfig.name,
    template: `%s - ${siteConfig.subName}`,
  },
  description: 'Generated by create next app',
  icons: '/icon.png',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="scroll-smooth font-sans antialiased">
        <RQProvider>
          {children}
          <Toaster richColors />
        </RQProvider>
      </body>
    </html>
  )
}
